#!/usr/bin/env bash
set -eu

elm make src/{MetadataTab.elm,AnalysisTab.elm} --output elm-bundle.js
mv elm-bundle.js ../django/miracle/core/templates/includes/.

touch ../django/deploy/uwsgi/miracle.ini
