"""
Django settings for miracle project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

from __future__ import print_function

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import sys


# tweaking standard BASE_DIR because we're in the settings subdirectory.
BASE_DIR = os.path.dirname(os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir)))
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

DJANGO_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
)

THIRD_PARTY_APPS = (
    'django_extensions',
    'bootstrap3',
    'social.apps.django_app.default',
    'raven.contrib.django.raven_compat',
)

MIRACLE_APPS = (
    'miracle.core',
)

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + MIRACLE_APPS

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

# authentication backends for python social auth
# http://python-social-auth.readthedocs.org/en/latest/configuration/django.html
# http://www.artandlogic.com/blog/2014/04/tutorial-adding-facebooktwittergoogle-authentication-to-a-django-application/
# https://docs.djangoproject.com/en/1.8/topics/auth/customizing/#authentication-backends

AUTHENTICATION_BACKENDS = (
    'social.backends.github.GithubOAuth2',
    'social.backends.facebook.FacebookOAuth2',
    'social.backends.google.GoogleOAuth2',
    'social.backends.twitter.TwitterOAuth',
    'django.contrib.auth.backends.ModelBackend',
)

ROOT_URLCONF = 'miracle.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.debug',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',
                # python-social-auth context processors
                'social.apps.django_app.context_processors.backends',
                'social.apps.django_app.context_processors.login_redirect',
                # expose SCM revision management to templates: https://github.com/klen/dealer
                'dealer.contrib.django.context_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'miracle.wsgi.application'


# Database configuration for metadata and ingested data
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'miracle_metadata',
        'USER': 'miracle',
        'PASSWORD': '',
    },
    'datasets': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'miracle_data',
        'USER': 'miracle',
        'PASSWORD': '',
    }
}

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = False

USE_L10N = False

# Logging
# https://docs.djangoproject.com/en/1.8/topics/logging/


def is_accessible(directory_path):
    return os.path.isdir(directory_path) and os.access(directory_path, os.W_OK | os.X_OK)

LOG_DIRECTORY = '/opt/miracle/logs'

if not is_accessible(LOG_DIRECTORY):
    try:
        os.makedirs(LOG_DIRECTORY)
    except OSError:
        print("Cannot create absolute log directory [%s]. Using relative path 'logs' instead" % LOG_DIRECTORY,
              file=sys.stderr)
        LOG_DIRECTORY = 'logs'
        if not is_accessible(LOG_DIRECTORY):
            try:
                os.makedirs(LOG_DIRECTORY)
            except OSError:
                print("Couldn't create any log directory, startup will fail", file=sys.stderr)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'root': {
        'level': 'INFO',
        'handlers': ['sentry', 'miracle.file', 'console'],
    },
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s [%(name)s|%(funcName)s:%(lineno)d] %(message)s'
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'handlers': {
        'sentry': {
            'level': 'ERROR',
            'formatter': 'verbose',
            'class': 'raven.contrib.django.raven_compat.handlers.SentryHandler',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'miracle.file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'formatter': 'verbose',
            'filename': os.path.join(LOG_DIRECTORY, 'miracle.log'),
            'backupCount': 6,
            'maxBytes': 10000000,
        },
    },
    'loggers': {
        'django.db.backends': {
            'level': 'ERROR',
            'handlers': ['console'],
            'propagate': False,
        },
        'raven': {
            'level': 'DEBUG',
            'handlers': ['console'],
            'propagate': False,
        },
        'sentry.errors': {
            'level': 'DEBUG',
            'handlers': ['console'],
            'propagate': False,
        },
        'miracle': {
            'level': 'DEBUG',
            'handlers': ['miracle.file', 'console'],
            'propagate': False,
        },
    }
}

USE_TZ = True

LOGIN_URL = "/account/login/"
LOGIN_REDIRECT_URL = '/dashboard/'

# Django REST Framework configuration, see http://www.django-rest-framework.org/api-guide/settings/
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.TemplateHTMLRenderer',
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    )
}

# Media files, see https://docs.djangoproject.com/en/1.8/ref/settings/#std:setting-MEDIA_ROOT for more details
# This absolute path specifies where all uploaded datasets will be sent. Can be overridden in local.py
MIRACLE_DATA_DIRECTORY = MEDIA_ROOT = '/opt/miracle/data/'
OUTPUT_FILE_PATH = '/opt/miracle/data/output'
MIRACLE_ANALYSIS_DIRECTORY = os.path.join(MIRACLE_DATA_DIRECTORY, "analyses")

if not is_accessible(MIRACLE_ANALYSIS_DIRECTORY):
    try:
        os.makedirs(MIRACLE_ANALYSIS_DIRECTORY)
    except OSError:
        print("Cannot create absolute analysis directory [%s]. Using relative path 'analyses' instead" % MIRACLE_ANALYSIS_DIRECTORY,
              file=sys.stderr)
        MIRACLE_ANALYSIS_DIRECTORY = 'analyses'
        if not is_accessible(MIRACLE_ANALYSIS_DIRECTORY):
            try:
                os.makedirs(MIRACLE_ANALYSIS_DIRECTORY)
            except OSError:
                print("Couldn't create any analyses directory, startup will fail", file=sys.stderr)

MEDIA_URL = '/data/'

# Celery settings: http://celery.readthedocs.org

CELERY_BROKER_URL = 'redis+socket:///var/lib/redis/redis.sock'
CELERY_RESULT_BACKEND = 'redis'

# DeployR settings
DEFAULT_DEPLOYR_USER = 'miracle'
DEFAULT_DEPLOYR_PASSWORD = ''
DEPLOYR_URL = 'https://deployr.comses.net/deployr'



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = "/var/www/miracle/static/"

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'miracle', 'static'),
)
